// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdkntocfbnlmiflplcgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ka250b2NmYm5sbWlmbHBsY2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NDc1ODAsImV4cCI6MjA5MDEyMzU4MH0.EqW1wnQMtIG3lQPCsc8NxWVHHodQqEOPc6cDJay7A1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});